### PR TITLE
filter-projects: fix bug where kiez filter only worked when there also was a district filter set

### LINKED ISSUE #6236: Kiezradar: filtering for a user created kiez doesn't work
**URL:** 
```/kiezradar/```

**user:** 
users with an account

**expected behaviour:** 
When users have created a personal Kiez in ```/account/kiezradar/``` they can use it in the Kiezradar to filter for projects in that area. 

**behaviour:** 
Selecting a user created kiez and applying the selection does not filter the list of projects and plans. Instead all projects and plans are shown, as if no filter has been applied.

### PR DESCRIPTION
**Pull request by vellip**
**Describe your changes**
fixes #6236

**Tasks**
- [ ] PR name contains story or task reference
- [ ] Steps to recreate and test the changes
- [ ] Documentation (docs and inline)
- [ ] Tests (including n+1 and django_assert_num_queries where applicable)
- [ ] Changelog

### CODE REVIEW

**Review by sevfurneaux — APPROVED** [review]

File: meinberlin/react/projects/filter-projects.js [hunk 1]
```diff
@@ -28,21 +28,31 @@ export const filterProjects = (items, appliedFilters, kiezradars, topics, projec
...
+      (search === '' ||
+        isInTitle(item.title, search) ||
+        isInTitle(item.district, search) ||
+        isInTitle(item.organisation, search) ||
+        isInTitle(item.description, search) ||
+        isInTopic(topics, item.topics, search)) &&
+      (projectState.includes(statusNames[item.status])) &&
+      (!plansOnly || item.type === 'plan') &&
+      (hasKiezradarAndDistrict
+        // if we have both active we want to include projects that are within kiez
```
Comment (sevfurneaux) [inline meinberlin/react/projects/filter-projects.js:46]: @vellip Thanks for fixing this!

Appreciate the comment here, as admittedly I find this whole logic quite hard to read and understand 🧠. Maybe it can be encapsulated in a named variable in the future?

Comment (vellip) [reply meinberlin/react/projects/filter-projects.js:46]: Definitely sounds like an idea!
