### PR TITLE
Mn 2019 12 fixes

### LINKED ISSUE #2675: testing 2394: deleting published/running modules should not be easily possible
**URL:** https://meinberlin-dev.liqd.net/dashboard/projects/testing-dashbaord/basic/
**user:** initiator
**expected behaviour:** cannot delete a published/running module easily 
**behaviour:** Initiator can delete a module from a published project without getting a notification. 
**important screensize:**
**device & browser:** 
**Comment/Question:** I suggest only to allow deleting a module not attached to the project.

### LINKED ISSUE #2677: testing 2394: Navigation minimization - part 2
**URL:** https://meinberlin-dev.liqd.net/dashboard/projects/testing-dashbaord/basic/
**user:** initiator
**expected behaviour:** after saving a form I can minimize/open navigation and go to a different form.
**behaviour:** after minimize/opening my navigation and going to a different form, I get a warning even if I have saved my form before changing navigation.
**important screensize:**
**device & browser:** 
**Comment/Question:**

### PR DESCRIPTION
**Pull request by MagdaN**
fixes #2677 
fixes #2675

### CODE REVIEW

File: meinberlin/apps/contrib/static/js/unload_warning.js [hunk 1]
```diff
@@ -3,6 +3,10 @@
 $(function () {
   var submitted = false
   var changeHandler = function () {
+    var target = event.target.id
+    if (target.includes('dashboard-nav')) {
```
Comment (fuzzylogic2000) [inline meinberlin/apps/contrib/static/js/unload_warning.js]: They do all have that in their id? Supercool!
